spring:
  jpa:
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false
    show-sql: true
    defer-datasource-initialization: false

  datasource:
    url: jdbc:h2:file:./eduquiz-db

  liquibase:
    change-log: db/changelog-dev.yml

  h2:
    console:
      enabled: true
      path: /eduquiz-h2

server:
  port: 8080